// main.rs
mod ast;
mod lexer;

// Include the parser generated by LALRPOP
lalrpop::lalrpop_mod!(pub parser); // this will generate parser.rs

use crate::ast::*;
use crate::lexer::Token;
use parser::ProgramParser;

fn main() {
    let input = r#"
        let x = 5;
        let y = Some(x + 3);
    "#;

    // Convert input into tokens using your Logos lexer
    let lex = lexer::Lexer::new(input)
        .map(|tok| tok.unwrap())
        .collect::<Vec<Token>>();

    // Parse tokens
    match ProgramParser::new().parse(&lex) {
        Ok(ast) => println!("AST: {ast:?}"),
        Err(e) => eprintln!("Parse error: {e}"),
    }
}
